# Joint movement bound per input coordinate
jointwise_angle_bounds: 
  # Index finger angles
  - 0.05
  - 0.2
  - 0.2
  - 0.2
  # Middle finger angles
  - 0.05
  - 0.2
  - 0.2
  - 0.2
  # Ring finger angles
  - 0.05
  - 0.2
  - 0.2
  - 0.2
  # Thumb finger angles
  - 0.2
  - 0.1
  - 0.2
  - 0.2

# Moving average time steps
time_steps: 3

# General info
total_num_joints: 16
joints_per_finger: 4

# Ros related info
joint_angle_topic: '/allegroHand_0/joint_states'

# Fingers and their offsets
fingers:
  index:
    name: 'Index'
    offset: 0
  
  middle:
    name: 'Middle'
    offset: 4

  ring:
    name: 'Ring'
    offset: 8

  thumb:
    name: 'Thumb'
    offset: 12

#  Finger info
links_info:

  # Base link 
  base:
    name: 'Base'
    link: 'base_link'

  # Index link
  index:
    name: 'Index'
    link: 'joint_0.0'
    offset: 0
    joint_min: 
      - -0.47
      - -0.196 
      - -0.174
      - -0.227
    joint_max: 
      - 0.47
      - 1.61
      - 1.709
      - 1.618

  # Middle link
  middle:
    name: 'Middle'
    link: 'joint_4.0'
    offset: 4
    joint_min: 
      - -0.47
      - -0.196 
      - -0.174
      - -0.227
    joint_max: 
      - 0.47
      - 1.61
      - 1.709
      - 1.618
  
  # Ring link
  ring:
    name: 'Ring'
    link: 'joint_8.0'
    offset: 8
    joint_min: 
      - -0.47
      - -0.196 
      - -0.174
      - -0.227
    joint_max: 
      - 0.47
      - 1.61
      - 1.709
      - 1.618

  # Thumb link
  thumb:
    name: 'Thumb'
    link: 'joint_12.0'
    offset: 12
    joint_min: 
      - 0.263 
      - -0.105
      - -0.189
      - -0.162
    joint_max: 
      - 1.396
      - 2
      - 1.644
      - 1.719